name: Windows Artifacts

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: cargo build --verbose --release
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hplc-rs
          path: ./target/release/HPLC-RS.exe